//! Hendrix Localization engine: detection, extraction from the sheet, and the
//! additive export round-trip (a translated sheet keeps every original column
//! byte-for-byte and only appends the target-language column).

use app_lib::engine::{self, hendrix, ExtractOpts};
use app_lib::model::{Status, UnitKind};
use std::path::Path;

const HEADER: &str = "Change,Excluded,Name,Original,jp,en";

/// Build a minimal Hendrix game: RPGMaker data fingerprint, an active
/// `Hendrix_Localization` plugin (with a jp/en language list), and a sheet whose
/// rows exercise a speaker, a choice, an excluded row, and a quoted cell holding a
/// comma + embedded newline.
fn make_game(root: &Path) {
    std::fs::create_dir_all(root.join("data")).unwrap();
    std::fs::write(root.join("data/System.json"), "{}").unwrap();

    // A real `js/plugins.js`: the Hendrix plugin's `Languages` param is a JSON
    // string whose elements are themselves JSON strings of `{Symbol, ...}` objects
    // (jp + en already present). Written as a raw literal to get the triple layer
    // of quoting exactly right.
    let plugins = r#"// Generated by RPG Maker.
var $plugins =
[
{"name":"Hendrix_Localization","status":true,"description":"","parameters":{"Languages":"[\"{\\\"Symbol\\\":\\\"jp\\\"}\",\"{\\\"Symbol\\\":\\\"en\\\"}\"]"}}
];
"#;
    std::fs::create_dir_all(root.join("js")).unwrap();
    std::fs::write(root.join("js/plugins.js"), plugins).unwrap();

    // Note the BOM and the quoted multiline/comma cell on the last data row.
    let sheet = format!(
        "\u{feff}{HEADER}\n\
         NEW,,アリス,こんにちは,こんにちは,Hi\n\
         NEW,x,ボブ,これは訳さない,これは訳さない,skip me\n\
         NEW,,,はい,はい,Yes\n\
         NEW,,ナレーター,\"雨が降る、\nそして風。\",\"雨が降る、\nそして風。\",\"Rain, and wind.\"\n"
    );
    std::fs::write(root.join("game_messages.csv"), sheet).unwrap();
}

#[test]
fn detects_hendrix_over_plain_rpgmaker() {
    let tmp = tempfile::tempdir().unwrap();
    make_game(tmp.path());
    let eng = engine::detect(tmp.path()).expect("should detect a game");
    // The Hendrix engine must win over mvmz for a sheet-localized game.
    assert_eq!(eng.id(), "rpgmaker-hendrix");
    let d = eng.describe(tmp.path()).unwrap();
    assert_eq!(d.engine_id, "rpgmaker-hendrix");
}

#[test]
fn extracts_original_column_with_speaker_and_skips_excluded() {
    let tmp = tempfile::tempdir().unwrap();
    make_game(tmp.path());
    let eng = engine::detect(tmp.path()).unwrap();
    let units = eng.extract(tmp.path(), &ExtractOpts::default()).unwrap();

    let sources: Vec<&str> = units.iter().map(|u| u.source.as_str()).collect();
    assert!(sources.contains(&"こんにちは"));
    assert!(sources.contains(&"はい"));
    assert!(sources.contains(&"雨が降る、\nそして風。")); // quoted, multiline cell
    assert!(!sources.contains(&"これは訳さない")); // Excluded row dropped

    let hi = units.iter().find(|u| u.source == "こんにちは").unwrap();
    assert_eq!(hi.kind, UnitKind::Dialogue);
    assert_eq!(hi.context.as_deref(), Some("アリス"));
    let yes = units.iter().find(|u| u.source == "はい").unwrap();
    assert_eq!(yes.kind, UnitKind::Other); // no speaker
}

#[test]
fn roundtrip_identity() {
    // Translate every unit to itself and export. The additive export must leave the
    // sheet's original columns byte-for-byte intact: re-extraction reproduces the
    // exact same sources, and only a `th` column is appended.
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    make_game(root);
    let eng = engine::detect(root).unwrap();

    let before: Vec<String> = eng
        .extract(root, &ExtractOpts::default())
        .unwrap()
        .into_iter()
        .map(|u| u.source)
        .collect();

    let mut units = eng.extract(root, &ExtractOpts::default()).unwrap();
    for u in &mut units {
        u.translation = Some(u.source.clone());
        u.status = Status::Draft;
    }
    // root == base for an MZ game. No backup / no font.
    let ex = hendrix::export_sheet(root, root, &units, false, false).unwrap();
    assert!(ex.note.contains("ไทย"));

    // Header gained exactly one column: th.
    let sheet = std::fs::read_to_string(root.join("game_messages.csv")).unwrap();
    let header = sheet.lines().next().unwrap();
    assert!(header.trim_end().ends_with(",th"), "th column appended: {header}");

    // Re-extraction from the exported sheet yields identical sources — the Original
    // column (and every other original column) survived untouched.
    let after: Vec<String> = eng
        .extract(root, &ExtractOpts::default())
        .unwrap()
        .into_iter()
        .map(|u| u.source)
        .collect();
    assert_eq!(before, after, "original columns must be unchanged by export");
}

#[test]
fn export_registers_language_and_reexport_is_idempotent() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    make_game(root);
    let eng = engine::detect(root).unwrap();
    let units = eng.extract(root, &ExtractOpts::default()).unwrap();

    hendrix::export_sheet(root, root, &units, false, false).unwrap();
    let first = std::fs::read_to_string(root.join("game_messages.csv")).unwrap();

    // The in-game language menu now offers th alongside jp/en.
    assert_eq!(registered_symbols(root), vec!["jp", "en", "th"]);

    // Re-export reproduces the same sheet and doesn't double the column/language.
    hendrix::export_sheet(root, root, &units, false, false).unwrap();
    let second = std::fs::read_to_string(root.join("game_messages.csv")).unwrap();
    assert_eq!(first, second, "re-export is byte-stable");
    assert_eq!(registered_symbols(root), vec!["jp", "en", "th"]);
}

/// The `Symbol` of every language registered in the Hendrix plugin, in order.
fn registered_symbols(root: &Path) -> Vec<String> {
    let text = std::fs::read_to_string(root.join("js/plugins.js")).unwrap();
    let (s, e) = (text.find('[').unwrap(), text.rfind(']').unwrap());
    let arr: Vec<serde_json::Value> = serde_json::from_str(&text[s..=e]).unwrap();
    let hendrix = arr
        .iter()
        .find(|p| p.get("name").and_then(|v| v.as_str()) == Some("Hendrix_Localization"))
        .unwrap();
    let langs_str = hendrix["parameters"]["Languages"].as_str().unwrap();
    let langs: Vec<String> = serde_json::from_str(langs_str).unwrap();
    langs
        .iter()
        .map(|l| {
            serde_json::from_str::<serde_json::Value>(l).unwrap()["Symbol"]
                .as_str()
                .unwrap()
                .to_string()
        })
        .collect()
}
