//! `xunity` engine: detect → extract → translate → export, against the single
//! BepInEx English cache layout supported by this app.
//!
//! This is the route for a game the app can't open natively — Unity above all.
//! XUnity hooks the game's text components at runtime and reads these files, so
//! translating them here means a real model (glossary, personas, TM) instead of
//! XUnity's machine-translation endpoints, with no game file touched.

use app_lib::engine::{self, ExtractOpts, GameEngine};
use app_lib::model::Status;
use app_lib::project::{self, db};
use std::path::{Path, PathBuf};

/// The shape XUnity dumps: comments, a directive, filled and empty entries, a
/// regex rule, CRLF line endings.
const DUMP: &str = "// AutoTranslator generated\r\n\
    \r\n\
    Start Game=\r\n\
    Load Game=\r\n\
    続ける=Continue\r\n\
    <b>Warning</b>: low battery=\r\n\
    Repair the {{A}} for [1] coins=\r\n\
    Already Thai=มีอยู่แล้ว\r\n";

fn write(root: &Path, rel: &str, s: &str) {
    let p = root.join(rel);
    std::fs::create_dir_all(p.parent().unwrap()).unwrap();
    std::fs::write(p, s).unwrap();
}

/// A Unity game folder with XUnity installed. The English cache is the only input
/// this engine recognizes; its runtime may be Mono or IL2CPP without changing this
/// file contract.
fn temp_game() -> (tempfile::TempDir, PathBuf) {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path().join("game");
    std::fs::create_dir_all(&root).unwrap();
    std::fs::write(root.join("winhttp.dll"), b"stub").unwrap();
    write(
        &root,
        "Game_Data/StreamingAssets/notes.txt",
        "Key=Value\r\n",
    );
    write(&root, "readme.txt", "Name=Value\r\n");
    write(
        &root,
        "BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt",
        DUMP,
    );
    write(
        &root,
        "BepInEx/Translation/ja/Text/_AutoGeneratedTranslations.txt",
        "Japanese cache=ignored\r\n",
    );
    write(
        &root,
        "BepInEx/Translation/en/Text/manual.txt",
        "Manual cache=ignored\r\n",
    );
    (tmp, root)
}

fn engine_for(root: &Path) -> Box<dyn GameEngine> {
    engine::detect(root).expect("an XUnity translation tree is detected")
}

#[test]
fn detect_picks_only_the_english_generated_cache() {
    let (_tmp, root) = temp_game();
    let eng = engine_for(&root);
    assert_eq!(eng.id(), "xunity");

    let d = eng.describe(&root).unwrap();
    assert_eq!(d.file_count, 1, "only the requested cache: {d:?}");

    let units = eng.extract(&root, &ExtractOpts::default()).unwrap();
    let keys: Vec<&str> = units.iter().map(|u| u.source.as_str()).collect();
    assert_eq!(
        keys,
        vec![
            "Start Game",
            "Load Game",
            "続ける",
            "<b>Warning</b>: low battery",
            "Repair the {{A}} for [1] coins",
            "Already Thai",
        ],
        "entries from the one cache; other cache files are ignored"
    );
    // A game `.txt` outside Translation/ must never become a unit.
    assert!(!keys.contains(&"Japanese cache"), "wrong locale leaked in");
    assert!(!keys.contains(&"Manual cache"), "manual cache leaked in");
}

#[test]
fn left_hand_original_is_the_source_and_english_cache_stays_eligible() {
    let (_tmp, root) = temp_game();
    let units = engine_for(&root)
        .extract(&root, &ExtractOpts::default())
        .unwrap();
    let unit = units.iter().find(|u| u.source == "続ける").unwrap();
    assert_eq!(unit.translation.as_deref(), Some("Continue"));
    assert_eq!(unit.status, Status::Untranslated);
}

#[test]
fn cached_right_hand_text_is_not_treated_as_completed_translation() {
    let (_tmp, root) = temp_game();
    let units = engine_for(&root)
        .extract(&root, &ExtractOpts::default())
        .unwrap();
    let cached = units.iter().find(|u| u.source == "Already Thai").unwrap();
    assert_eq!(cached.status, Status::Untranslated);
    assert_eq!(cached.translation.as_deref(), Some("มีอยู่แล้ว"));

    let todo = units.iter().find(|u| u.source == "Start Game").unwrap();
    assert_eq!(todo.status, Status::Untranslated, "empty value = to-do");
    assert_eq!(todo.translation, None);
}

#[test]
fn roundtrip_identity() {
    let (_tmp, root) = temp_game();
    let eng = engine_for(&root);
    let mut units = eng.extract(&root, &ExtractOpts::default()).unwrap();
    // Write every unit's own current value back — output must be byte-identical.
    for u in &mut units {
        u.translation = Some(u.translation.clone().unwrap_or_default());
        u.status = Status::Translated;
    }
    eng.inject(&root, &units, &root).unwrap();

    assert_eq!(
        std::fs::read_to_string(
            root.join("BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt")
        )
        .unwrap(),
        DUMP
    );
}

/// The whole point: open the game folder as a project, translate, export — the
/// files XUnity reloads (ALT+R) come back filled in, with everything else intact.
#[test]
fn open_translate_export_fills_the_files() {
    let (_tmp, root) = temp_game();
    let (mut proj, fresh) = project::open_or_create(&root, "en", "Thai").unwrap();
    assert!(fresh, "first open extracts");
    assert_eq!(proj.info(fresh).unwrap().engine_id, "xunity");

    for u in &db::all_units(&proj.conn).unwrap() {
        let tr = match u.source.as_str() {
            "Start Game" => "เริ่มเกม",
            "Load Game" => "โหลดเกม",
            "続ける" => "ดำเนินการต่อ",
            _ => continue,
        };
        db::update_unit(&proj.conn, u.id, Some(tr), "Translated").unwrap();
    }
    let res = project::export(&mut proj, true, false).unwrap();
    assert_eq!(res.files_written, 1);

    let out = std::fs::read_to_string(
        root.join("BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt"),
    )
    .unwrap();
    assert!(out.contains("Start Game=เริ่มเกม\r\n"), "{out}");
    assert!(out.contains("Load Game=โหลดเกม\r\n"), "{out}");
    assert!(out.contains("続ける=ดำเนินการต่อ\r\n"), "{out}");
    assert!(
        out.contains("// AutoTranslator generated"),
        "comment kept: {out}"
    );
    assert!(
        out.contains("Already Thai=มีอยู่แล้ว\r\n"),
        "pre-existing translation untouched: {out}"
    );
    assert!(
        out.contains("<b>Warning</b>: low battery=\r\n"),
        "an untranslated entry stays empty: {out}"
    );

    // Re-export must reproduce the same bytes (the `.rpgtl/source/` snapshot rule).
    let again = project::export(&mut proj, false, false).unwrap();
    assert_eq!(again.files_written, 1);
    assert_eq!(
        std::fs::read_to_string(
            root.join("BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt")
        )
        .unwrap(),
        out,
        "re-export is idempotent"
    );
}

/// A mod export builds the same tree in a zip, leaving the game untouched — for
/// handing a translation to someone who already has XUnity installed.
#[test]
fn mod_export_carries_the_translation_files() {
    use std::io::Read;

    let (_tmp, root) = temp_game();
    let (proj, _) = project::open_or_create(&root, "en", "Thai").unwrap();
    for u in &db::all_units(&proj.conn).unwrap() {
        if u.source == "Start Game" {
            db::update_unit(&proj.conn, u.id, Some("เริ่มเกม"), "Translated").unwrap();
        }
    }
    let before = std::fs::read_to_string(
        root.join("BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt"),
    )
    .unwrap();

    let r = project::export_mod(&proj, false).unwrap();
    assert!(Path::new(&r.zip_path).is_file());

    let f = std::fs::File::open(&r.zip_path).unwrap();
    let mut zip = zip::ZipArchive::new(f).unwrap();
    let mut e = zip
        .by_name("BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt")
        .expect("translation file in the mod zip");
    let mut s = String::new();
    e.read_to_string(&mut s).unwrap();
    assert!(s.contains("Start Game=เริ่มเกม\r\n"), "{s}");

    // The game's own copy is untouched by a mod export.
    assert_eq!(
        std::fs::read_to_string(
            root.join("BepInEx/Translation/en/Text/_AutoGeneratedTranslations.txt")
        )
        .unwrap(),
        before
    );
}
